jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Proyecto\PrincipalBundle\Entity\Usuario:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: ProyectoPrincipalBundle:Usuario, property: username }

    firewalls:
        secured_area:
            pattern:    ^/modulo
            anonymous: ~
            form_login:
                login_path:  /acceso
                check_path:  /modulo/login_check
                default_target_path: /modulo/
            logout:
              path: /logout
              target: /
    access_control:
        - { path: ^/modulo, roles: ROLE_ADMIN }
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }