proyecto_principal_homepage:
    pattern:  /
    defaults: { _controller: ProyectoPrincipalBundle:Default:index }
proyecto_principal_editar:
    pattern:  /editar
    defaults: { _controller: ProyectoPrincipalBundle:Default:editar }
proyecto_principal_acerca:
    pattern:  /acerca
    defaults: { _controller: ProyectoPrincipalBundle:Default:acerca }
proyecto_principal_validacion:
    pattern:  /validacion
proyecto_principal_nuevo:
    pattern:  /nuevo
    defaults: { _controller: ProyectoPrincipalBundle:Default:nuevo }
login:
    pattern:   /login
    defaults:  { _controller: AcmeSecurityBundle:Security:login }
login_check:
    pattern:   /login_check

proyecto_principal_acceso:
    pattern:  /acceso
    defaults: { _controller: ProyectoPrincipalBundle:Users:acceso }
proyecto_principal_registro:
    pattern:  /registro
    defaults: { _controller: ProyectoPrincipalBundle:Users:registro }
proyecto_principal_cuenta_guardar:
    pattern:  /cuenta/guardar
    defaults: { _controller: ProyectoPrincipalBundle:Users:cuentaGuardar }
    requirements:
      _method: POST
proyecto_principal_cerrarsesion:
    pattern:  /logout
    defaults: { _controller: ProyectoPrincipalBundle:Users:acceso }
proyecto_principal_perfil:
    pattern:  /perfil
    defaults: { _controller: ProyectoPrincipalBundle:Users:perfil }
