parameters:
#    proyecto_principal.example.class: Proyecto\PrincipalBundle\Example

services:
#    proyecto_principal.example:
#        class: %proyecto_principal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
